### ISSUE TITLE
"Too many arguments" error when running the app

### ISSUE THREAD

**Issue by amitramon** [lrsxcd/vip-repl#11]
When doing "npm run dev" the app starts but then I get the following output (when trying to access localhost:3000 get a blank page, but no HTTP error, like the server is running):

shadow-cljs - HTTP server for :app available at http://localhost:3000
shadow-cljs - server version: 2.7.25 running at http://localhost:9630
shadow-cljs - nREPL server started on port 3333
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build failure:
------ ERROR -------------------------------------------------------------------
 File: /home/amit/projects/SLR/vip-repl/examples/withshadow/src/app/vip_repl_api.cljs
null
{:clojure.error/source "app/vip_repl_api.cljs", :clojure.error/line 10, :clojure.error/column 1, :clojure.error/phase :compilation}
ExceptionInfo: 
	clojure.core/ex-info (core.clj:4739)
	clojure.core/ex-info (core.clj:4739)
	cljs.analyzer/analyze-seq*-wrap (analyzer.cljc:3849)
	cljs.analyzer/analyze-seq*-wrap (analyzer.cljc:3848)
	cljs.analyzer/analyze-seq (analyzer.cljc:3874)
	cljs.analyzer/analyze-seq (analyzer.cljc:3852)
	cljs.analyzer/analyze-form (analyzer.cljc:4061)
	cljs.analyzer/analyze-form (analyzer.cljc:4058)
	cljs.analyzer/analyze* (analyzer.cljc:4111)
	cljs.analyzer/analyze* (analyzer.cljc:4102)
	shadow.build.compiler/analyze (compiler.clj:212)
	shadow.build.compiler/analyze (compiler.clj:176)
	shadow.build.compiler/analyze (compiler.clj:178)
	shadow.build.compiler/analyze (compiler.clj:176)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:314)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:303)
	clojure.core/partial/fn--5561 (core.clj:2617)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:257)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:215)
	shadow.build.compiler/analyze-cljs-string/fn--11646 (compiler.clj:378)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:377)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:375)
	shadow.build.compiler/do-compile-cljs-resource/fn--11667 (compiler.clj:471)
	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:453)
	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:411)
	shadow.build.compiler/maybe-compile-cljs/fn--11753 (compiler.clj:736)
	shadow.build.compiler/maybe-compile-cljs (compiler.clj:735)
	shadow.build.compiler/maybe-compile-cljs (compiler.clj:711)
	shadow.build.compiler/par-compile-one (compiler.clj:837)
	shadow.build.compiler/par-compile-one (compiler.clj:792)
	shadow.build.compiler/par-compile-cljs-sources/fn--11787/iter--11809--11813/fn--11814/fn--11815/fn--11816 (compiler.clj:910)
	clojure.core/apply (core.clj:657)
	clojure.core/with-bindings* (core.clj:1965)
	clojure.core/with-bindings* (core.clj:1965)
	clojure.core/apply (core.clj:661)
	clojure.core/bound-fn*/fn--5471 (core.clj:1995)
	java.util.concurrent.FutureTask.run (FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
	java.lang.Thread.run (Thread.java:748)
Caused by:
Too many arguments to def at line 10 app/vip_repl_api.cljs

**Comment by davidvoler** [comment]
The file vip_repl_api.cljs was not ready yet
I have commented out the reference to this file from core.cljs file 
now the error is not there anymore
